// ============================================================
// xphage-doc — Documentation Generator v3.5.0
//
// Parses .xp0 and .xh files for /// doc comments
// and generates a Markdown + HTML reference.
//
// Usage:
//   xphage-doc <src_dir> [--out <out_dir>] [--format md|html]
// ============================================================
#include "xphage/runtime.hpp"
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <filesystem>
#include <algorithm>
#include <cstring>

namespace fs = std::filesystem;

// ── Doc entry ────────────────────────────────────────────────
struct DocEntry {
    std::string kind;       // "pulse" | "global" | "const" | "module"
    std::string name;
    std::string signature;
    std::string doc;        // joined /// lines
    std::string file;
    uint32_t    line = 0;
};

// ── Parser ───────────────────────────────────────────────────
static std::vector<DocEntry> parse_file(const std::string& path) {
    std::ifstream f(path);
    if (!f.is_open()) return {};

    std::vector<DocEntry> entries;
    std::string line;
    uint32_t lineno = 0;
    std::string pending_doc;

    while (std::getline(f, line)) {
        lineno++;
        // Trim leading whitespace
        size_t s = line.find_first_not_of(" \t");
        if (s == std::string::npos) { pending_doc.clear(); continue; }
        std::string trimmed = line.substr(s);

        // /// doc comment
        if (trimmed.rfind("///", 0) == 0) {
            std::string txt = trimmed.size() > 3 ? trimmed.substr(4) : "";
            if (!pending_doc.empty()) pending_doc += "\n";
            pending_doc += txt;
            continue;
        }

        // Detect declarations
        DocEntry entry;
        entry.file = path;
        entry.line = lineno;
        entry.doc  = pending_doc;
        pending_doc.clear();

        if (trimmed.rfind("pulse ", 0) == 0) {
            entry.kind = "pulse";
            size_t sp = trimmed.find(' ', 6);
            if (sp == std::string::npos) sp = trimmed.size();
            entry.name = trimmed.substr(6, sp - 6);
            // strip trailing {
            if (!entry.name.empty() && entry.name.back() == '{')
                entry.name.pop_back();
            entry.name.erase(entry.name.find_last_not_of(" ") + 1);
            entry.signature = trimmed;
            entries.push_back(entry);
        }
        else if (trimmed.rfind("global ", 0) == 0) {
            entry.kind = "global";
            size_t sp = trimmed.find(' ', 7);
            entry.name = (sp == std::string::npos)
                ? trimmed.substr(7) : trimmed.substr(7, sp - 7);
            entry.signature = trimmed;
            entries.push_back(entry);
        }
        else if (trimmed.rfind("#define ", 0) == 0) {
            entry.kind = "const";
            size_t sp = trimmed.find(' ', 8);
            entry.name = (sp == std::string::npos)
                ? trimmed.substr(8) : trimmed.substr(8, sp - 8);
            entry.signature = trimmed;
            entries.push_back(entry);
        }
    }
    return entries;
}

// ── Markdown generation ───────────────────────────────────────
static std::string to_markdown(const std::string& src_dir,
                                const std::vector<DocEntry>& entries) {
    std::ostringstream md;
    md << "# X-Phage API Reference\n\n";
    md << "> Generated by xphage-doc v3.5.0\n\n";
    md << "---\n\n";

    std::string cur_file;
    for (auto& e : entries) {
        if (e.file != cur_file) {
            cur_file = e.file;
            std::string rel = cur_file;
            if (rel.rfind(src_dir, 0) == 0)
                rel = rel.substr(src_dir.size() + 1);
            md << "## `" << rel << "`\n\n";
        }

        md << "### " << e.kind << " `" << e.name << "`\n\n";
        md << "```xp0\n" << e.signature << "\n```\n\n";
        if (!e.doc.empty()) {
            md << e.doc << "\n\n";
        }
        md << "---\n\n";
    }
    return md.str();
}

// ── HTML generation ───────────────────────────────────────────
static std::string to_html(const std::string& src_dir,
                             const std::vector<DocEntry>& entries) {
    std::ostringstream html;
    html << "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>\n";
    html << "<title>X-Phage API Reference</title>\n";
    html << "<style>\n"
         << "body{font-family:system-ui,sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem}\n"
         << "h1{color:#7c3aed}h2{color:#6d28d9;border-bottom:2px solid #e9d5ff;padding-bottom:.3rem}\n"
         << "h3{color:#4c1d95}pre{background:#1e1b4b;color:#e9d5ff;padding:1rem;border-radius:.5rem}\n"
         << "code{background:#f5f3ff;color:#4c1d95;padding:.1rem .3rem;border-radius:.2rem}\n"
         << ".kind{font-size:.75rem;background:#8b5cf6;color:#fff;padding:.1rem .4rem;border-radius:1rem;margin-right:.5rem}\n"
         << ".doc{color:#374151;margin:0.5rem 0}\n"
         << "hr{border:none;border-top:1px solid #e5e7eb}\n"
         << "</style></head><body>\n"
         << "<h1>🧬 X-Phage API Reference</h1>\n"
         << "<p><small>Generated by xphage-doc v3.5.0</small></p>\n";

    std::string cur_file;
    for (auto& e : entries) {
        if (e.file != cur_file) {
            cur_file = e.file;
            std::string rel = cur_file;
            if (rel.rfind(src_dir, 0) == 0)
                rel = rel.substr(src_dir.size() + 1);
            html << "<h2>" << rel << "</h2>\n";
        }
        html << "<div>\n";
        html << "<h3><span class='kind'>" << e.kind << "</span><code>"
             << e.name << "</code></h3>\n";
        html << "<pre><code>" << e.signature << "</code></pre>\n";
        if (!e.doc.empty())
            html << "<p class='doc'>" << e.doc << "</p>\n";
        html << "</div><hr>\n";
    }

    html << "</body></html>\n";
    return html.str();
}

// ── main ─────────────────────────────────────────────────────
int main(int argc, char* argv[]) {
    if (argc < 2) {
        std::cerr << "xphage-doc v3.5.0\n"
                  << "Usage: xphage-doc <src_dir> [--out <dir>] [--format md|html]\n";
        return 1;
    }

    std::string src_dir  = argv[1];
    std::string out_dir  = ".";
    std::string format   = "md";

    for (int i = 2; i < argc; i++) {
        if (std::strcmp(argv[i], "--out") == 0 && i + 1 < argc)
            out_dir = argv[++i];
        else if (std::strcmp(argv[i], "--format") == 0 && i + 1 < argc)
            format = argv[++i];
    }

    // Collect all .xp0 and .xh files
    std::vector<DocEntry> all_entries;
    std::error_code ec;
    for (auto& entry : fs::recursive_directory_iterator(src_dir, ec)) {
        if (!entry.is_regular_file()) continue;
        auto ext = entry.path().extension().string();
        if (ext == ".xp0" || ext == ".xh") {
            auto file_entries = parse_file(entry.path().string());
            all_entries.insert(all_entries.end(),
                               file_entries.begin(), file_entries.end());
        }
    }
    if (ec) {
        std::cerr << "Error reading directory: " << ec.message() << "\n";
        return 1;
    }

    // Sort by file then by line
    std::sort(all_entries.begin(), all_entries.end(),
        [](const DocEntry& a, const DocEntry& b) {
            return a.file < b.file || (a.file == b.file && a.line < b.line);
        });

    std::cout << "[xphage-doc] Found " << all_entries.size()
              << " documented items in " << src_dir << "\n";

    // Write output
    fs::create_directories(out_dir, ec);
    if (format == "html" || format == "both") {
        std::string html = to_html(src_dir, all_entries);
        std::ofstream f(out_dir + "/api.html");
        f << html;
        std::cout << "[xphage-doc] ✔ " << out_dir << "/api.html\n";
    }
    if (format == "md" || format == "both") {
        std::string md = to_markdown(src_dir, all_entries);
        std::ofstream f(out_dir + "/api.md");
        f << md;
        std::cout << "[xphage-doc] ✔ " << out_dir << "/api.md\n";
    }

    return 0;
}
