#include "../../../include/xphage/runtime.hpp"
#include <iostream>
#include <fstream>
#include <sstream>

/**
 * 🚀 X-Phage Titan Transpiler v1.0
 * Purpose: Converts X-Phage code to High-Performance C++17
 * Use Case: Mobile, Game Engines, Embedded Systems where LLVM is heavy.
 */

void XPhageTranspiler::transpile_to_cpp(const std::vector<Token>& tokens, std::string output_filename) {
    std::ofstream out(output_filename);
    
    // 1. Inject C++ Header Guard & Boilerplate
    out << "// Generated by X-Phage Titan Transpiler\n";
    out << "#include <iostream>\n";
    out << "#include <string>\n";
    out << "#include <vector>\n";
    out << "#include <thread>\n";
    out << "#include <cstdlib>\n\n";
    
    out << "int main() {\n";
    out << "    // --- Titan Memory Initialization ---\n";

    for (size_t i = 0; i < tokens.size(); ++i) {
        
        // GLOBAL -> std::string
        if (tokens[i].type == GLOBAL && i + 3 < tokens.size()) {
            std::string var = tokens[i+1].value;
            std::string val = tokens[i+3].value;
            out << "    std::string " << var << " = \"" << val << "\";\n";
            i += 3;
        }
        
        // BEAM -> std::cout
        else if (tokens[i].type == BEAM && i + 1 < tokens.size()) {
            std::string target = tokens[i+1].value;
            // Check if it's a variable or raw string
            if (target.front() == '"') {
                 out << "    std::cout << " << target << " << std::endl;\n";
            } else {
                 out << "    std::cout << " << target << " << std::endl;\n";
            }
            i++;
        }
        
        // BYPASS -> system()
        else if (tokens[i].type == BYPASS && i + 1 < tokens.size()) {
            out << "    system(\"" << tokens[i+1].value << "\");\n";
            i++;
        }

        // QUANTUM -> std::thread
        else if (tokens[i].type == QUANTUM && i + 1 < tokens.size()) {
             out << "    std::thread([](){ \n";
             out << "        std::cout << \"[Thread] Executing Quantum Task: " << tokens[i+1].value << "\" << std::endl;\n";
             out << "    }).detach();\n";
             i++;
        }
    }

    out << "    return 0;\n";
    out << "}\n";
    out.close();

    std::cout << "\033[1;36m[TRANSPILER] 🚀 Transpiled to Native C++: " << output_filename << "\033[0m\n";
}
