name: Mirror Code to Codeberg

on:
  push:
    branches:
      - main   #default branch

jobs:
  mirror-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Push to Codeberg
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add codeberg https://cybernahid-dev@codeberg.org/AeonCoreX/X-Phage.git
          git push codeberg main
        env:
          GIT_ASKPASS: /bin/echo
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}